language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kat201/docker-react-ci-course -f Dockerfile.dev .

script:
  - docker run -e CI=true kat201/docker-react-ci-course npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-ci-course"
  env: "DockerReactCiCourse-env"
  bucket_name: "elasticbeanstalk-us-east-1-001959195903"
  bucket_path: "docker-react-ci-course"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
